# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Username', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('Password', models.CharField(blank=True, max_length=20)),
                ('Email_Id', models.CharField(blank=True, max_length=35)),
                ('Address', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
