# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Address',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='Email_Id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='Username',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
