# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_auto_20171007_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Phone_No', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='Email_Id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='Username',
            field=models.ForeignKey(db_column='Account.Username', on_delete=django.db.models.deletion.CASCADE, to='railway.Account'),
        ),
    ]
