# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_auto_20171007_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
