# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_auto_20171007_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='Train_Fare',
            field=models.IntegerField(default=0),
        ),
    ]
