# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_train_train_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='Fare',
            field=models.IntegerField(default=0),
        ),
    ]
